export const movementCategories = ["Push", "Pull", "Dips", "Legs", "Core"] as const;
export type MovementCategory = (typeof movementCategories)[number];

export const progressions: Record<MovementCategory, string[]> = {
  Push: [
    "Wall",
    "Incline",
    "Knee",
    "Full",
    "Decline",
    "Diamond",
    "Archer",
    "Clap",
    "One-Arm Assisted",
    "One-Arm",
  ],
  Pull: [
    "Dead Hang",
    "Scapular",
    "Assisted",
    "Negative",
    "Jumping",
    "Half",
    "Full",
    "Close",
    "Wide",
    "Muscle-Up",
  ],
  Dips: [
    "Bench (feet on floor)",
    "Bench (elevated)",
    "Support Hold",
    "Assisted",
    "Negative",
    "Full",
    "Ring",
    "Korean",
    "Weighted",
    "Straight Bar",
  ],
  Legs: [
    "Chair",
    "Assisted",
    "Bodyweight",
    "Wide",
    "Narrow",
    "Bulgarian Split",
    "Pistol w/ Support",
    "Pistol",
    "Jump",
    "Shrimp",
  ],
  Core: [
    "Lying Knee",
    "Lying Leg",
    "Hanging Knee",
    "Hanging Leg",
    "Toes-to-Bar",
    "L-Sit",
    "Windshield",
    "Dragon Flag",
    "V-Up",
    "Front Lever",
  ],
};
